# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Accountant email automation
version: "3.2.0"
slug: accountant-email-automation
description: Sends a monthly email using a provided template and attachments.
url: "https://github.com/gilsonmandalogo/accountant-email-automation"
arch:
  - amd64
init: false
map:
  - type: addon_config
    path: /usr/src/app/private
image: "gilsonmjr/accountant-email-automation"