# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Accountant email automation
version: "6.2.0"
slug: accountant-email-automation
description: Sends a monthly email using a provided template and attachments.
url: "https://github.com/gilsonmandalogo/accountant-email-automation"
image: "gilsonmjr/accountant-email-automation"
init: false
ports:
  3000/tcp: 3000
arch:
  - amd64
webui: http://[HOST]:[PORT:3000]/
panel_icon: mdi:email-fast
watchdog: tcp://[HOST]:[PORT:3000]
tmpfs: true
homeassistant_api: true
schema:
  vendus_url: url
  vendus_user: str
  vendus_pass: password
  email_to: email
  email_subject: str
  email_template: str
