version: '3.8'

services:
  accountant-email-automation:
    container_name: accountant-email-automation
    image: gilsonmjr/accountant-email-automation:1
    volumes:
      - ./private/wise-statements.config.json:/root/.config/wise-statements/.config.json:ro
      - ./private/vendus-export.config.json:/root/.config/vendus-export/.config.json:ro
      - ./private/private.pem:/usr/src/app/private/private.pem:ro
      - ./private/.env:/usr/src/app/private/.env:ro
